import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar/Sidebar'
import GlobalStyleProvider from './providers/GlobalStyleProvider'
import ContextProviders from './providers/ContextProviders'
import { ClerkProvider, auth } from '@clerk/nextjs'
import NextTopLoader from 'nextjs-toploader'

const nunito = Nunito({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {userId} = auth();
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={nunito.className}>
        <NextTopLoader
        height={4}
        color= "#27ae60"
        easing='cubic-bezier(0.53, 0.21, 0, 1)'
         />
        <ContextProviders>

          <GlobalStyleProvider>
            {userId && <Sidebar />}
            <div className='w-full'>{children}</div>
          </GlobalStyleProvider>
        </ContextProviders>
      </body>
    </html>
    </ClerkProvider>
  )
}
